[package]
name = "autobuf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
tokio = {version = "1.17.0", features = ["rt", "macros"] }

[dependencies]
futures = "0.3.21"
